/*This file is generated by perlxml.pl. DO NOT MODIFY */

#import "AllergiesReactionsViewController.h"
#import "BBUtil.h"
#import "FormSection.h"
#import "FormElement.h"
#import "BBCheckBox.h"
#import "BooleanFormElement.h"
#import "StringListElement.h"
#import "TextElement.h"
#import "StringArrayTableAdapter.h"

#import "ElementListFormElement.h"

#import "FormElementTableAdapter.h"

#import "FormElementTableCellFactory.h"

#import "AntibioticFormElement.h"

#import "MedicationFormElement.h"

#import "BBData.h"

#import "BBAutoCompleteTextField.h"


@interface AllergiesReactionsViewController () <UITextFieldDelegate>
@property (weak, nonatomic) IBOutlet BBCheckBox *noKnownAllergiesBBCheckBox;
@property (weak, nonatomic) IBOutlet BBAutoCompleteTextField *allergiesReactionsTextField;
@property (weak, nonatomic) IBOutlet UITableView *allergiesReactionsTable;
@property (strong, nonatomic) StringArrayTableAdapter *allergiesReactionsTableAdapter;
@property (weak, nonatomic) IBOutlet UITextView *notesUITextView;
@end

@implementation AllergiesReactionsViewController
NSString *const ALLERGIES_REACTIONS_SECTION_TITLE = @"AllergiesReactionsSectionKey";
static NSString *const NO_KNOWN_ALLERGIES_KEY = @"NoKnownAllergiesKey";
static NSString *const ALLERGIES_REACTIONS_KEY = @"AllergiesReactionsKey";
static NSString *const NOTES_KEY = @"NotesKey";

- (void)viewDidLoad
{
	 [super viewDidLoad];
	 [_allergiesReactionsTextField setAutoCompleteData:[BBData allergies]];
	 self.allergiesReactionsTableAdapter = [[StringArrayTableAdapter alloc] init];
	 self.allergiesReactionsTable.dataSource = self.allergiesReactionsTableAdapter;
	 self.allergiesReactionsTable.delegate = self.allergiesReactionsTableAdapter;

	 if (_section) {
		 [self validateSection:_section];
		 NSArray *elements = [_section.elements array];

		 for (FormElement *element in elements) {
			 if ([element.key isEqualToString:NO_KNOWN_ALLERGIES_KEY]){
				 [self.noKnownAllergiesBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:ALLERGIES_REACTIONS_KEY]){
				 self.allergiesReactionsTableAdapter.items = [[NSMutableArray alloc] initWithArray:((StringListElement*)element).value];
				 [self.allergiesReactionsTable reloadData];
			 }
			 if ([element.key isEqualToString:NOTES_KEY]){
				 [self.notesUITextView setText:((TextElement*)element).value];
			 }
		 }
	 }
}


-(void)addDatePicker: (UITextField*)textField withSelector: (SEL)selector {
	 UIDatePicker *datePicker = [[UIDatePicker alloc] init];
	 datePicker.datePickerMode = UIDatePickerModeDate;
	 [textField setInputView:datePicker];
	 UIToolbar *myToolbar = [[UIToolbar alloc] initWithFrame: CGRectMake(0,0,340,44)];
	 UIBarButtonItem *doneButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:selector];
	 [myToolbar setItems:[NSArray arrayWithObject: doneButton] animated:NO];
	 textField.inputAccessoryView = myToolbar;
}

-(void)validateSection:(FormSection*)section
{
	 NSAssert([section getElementForKey:NO_KNOWN_ALLERGIES_KEY]!= nil, @"NoKnownAllergies is nil");
	 NSAssert([section getElementForKey:ALLERGIES_REACTIONS_KEY]!= nil, @"AllergiesReactions is nil");
	 NSAssert([section getElementForKey:NOTES_KEY]!= nil, @"Notes is nil");
	 
}

-(BOOL)validateData:(NSString**)errMsg
{
	 return true; 
}

- (IBAction)accept:(id)sender {
	 NSString* errMsg;
	 if ( ! [self validateData: &errMsg] ){
		 [BBUtil showAlertWithMessage:errMsg];
		 return;
	 }
	 if ( !self.section ){
		 self.section = (FormSection*)[BBUtil newCoreDataObjectForEntityName:@"FormSection"];
		 self.section.title = ALLERGIES_REACTIONS_SECTION_TITLE;
	 }
	 
	 BooleanFormElement *noKnownAllergies = (BooleanFormElement*)[_section getElementForKey:NO_KNOWN_ALLERGIES_KEY];
	 if (!noKnownAllergies) {
		 noKnownAllergies = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 noKnownAllergies.key = NO_KNOWN_ALLERGIES_KEY;
		 [_section addElementsObject:noKnownAllergies];
	 }

	 noKnownAllergies.value = [NSNumber numberWithBool:self.noKnownAllergiesBBCheckBox.isSelected];
	 
	 StringListElement *allergiesReactions = (StringListElement*)[_section getElementForKey:ALLERGIES_REACTIONS_KEY];
	 if (!allergiesReactions) {
		 allergiesReactions = (StringListElement*)[BBUtil newCoreDataObjectForEntityName:@"StringListElement"];
		 allergiesReactions.key = ALLERGIES_REACTIONS_KEY;
		 [_section addElementsObject:allergiesReactions];
	 }

	 NSMutableArray *allergiesReactionsStringArray = [[NSMutableArray alloc] init];
	 for (int i = 0; i < [self.allergiesReactionsTable numberOfRowsInSection:0]; i++){
		 UITableViewCell *cell = [self.allergiesReactionsTable cellForRowAtIndexPath:[NSIndexPath indexPathForRow:i inSection:0]];
		 [allergiesReactionsStringArray addObject:cell.textLabel.text];
	 }
	 allergiesReactions.value = allergiesReactionsStringArray;
	 
	 TextElement *notes = (TextElement*)[_section getElementForKey:NOTES_KEY];
	 if (!notes) {
		 notes = (TextElement*)[BBUtil newCoreDataObjectForEntityName:@"TextElement"];
		 notes.key = NOTES_KEY;
		 [_section addElementsObject:notes];
	 }

	 notes.value = self.notesUITextView.text;
	 
	 [self.delegate sectionCreated:self.section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

- (IBAction)changeMedUnit:(UIButton*)sender {
	 if ([sender.titleLabel.text isEqualToString: @"cc"]) { 
		 [sender setTitle:@"mcg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mcg"]) {
		 [sender setTitle:@"mg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mg"]) {
		 [sender setTitle:@"G" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"G"]) {
		 [sender setTitle:@"none" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"none"]) {
		 [sender setTitle:@"cc" forState:UIControlStateNormal];
	 } 
}

- (IBAction)addAllergiesReactions:(id)sender {
	 [self.allergiesReactionsTableAdapter.items addObject:self.allergiesReactionsTextField.text];
	 [self.allergiesReactionsTable reloadData];
	 self.allergiesReactionsTextField.text = @"";
	 [self.allergiesReactionsTextField resignFirstResponder];
}

- (BOOL)disablesAutomaticKeyboardDismissal {
	 return NO;
}

- (IBAction)dismiss:(id)sender {
	 [BBUtil refreshManagedObject:_section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

+(NSString*)sectionTitle
{
	 return ALLERGIES_REACTIONS_SECTION_TITLE;
}
-(void)radioGroup1:(BBCheckBox*)sender {
	 BOOL selected = sender.selected;
	 sender.selected = selected;
}
@end