//
//  BBData.m
//  iCare2
//
//  Created by billy bray on 8/30/14.
//  Copyright (c) 2014 Spartan Systems Inc. All rights reserved.
//

#import "BBData.h"


static NSArray *procedureArray;
static NSArray *medicationArray;
static NSArray *allergyArray;
@implementation BBData

+(NSArray*)procedures
{
    if (!procedureArray) {
        procedureArray = [[NSArray alloc] initWithObjects:
                          @"Abdominoperineal resection",
                          @"Above the knee amputation",
                          @"Adjustable gastric banding",
                          @"Allogenic bone marrow transplant",
                          @"Ankle fusion",
                          @"Anterior neck dissection",
                          @"Aortic Aneurysm Repair",
                          @"Aortic valve repair surgery",
                          @"Aortic valve replacement surgery",
                          @"Aortobifemoral bypass",
                          @"Aortofemoral bypass",
                          @"Appendectomy (Removal of Appendix)",
                          @"Arm fasciotomy",
                          @"Arthroscopic ankle replacement",
                          @"Arthroscopic ankle synovectomy",
                          @"Arthroscopic anterior cruciate ligament surgery",
                          @"Arthroscopic elbow replacement",
                          @"Arthroscopic elbow synovectomy",
                          @"Arthroscopic hip replacement",
                          @"Arthroscopic hip synovectomy",
                          @"Arthroscopic knee fusion",
                          @"Arthroscopic knee synovectomy",
                          @"Arthroscopic partial hip replacement",
                          @"Arthroscopic partial knee replacement",
                          @"Arthroscopic revision hip surgery",
                          @"Arthroscopic revision knee surgery",
                          @"Arthroscopic shoulder replacement",
                          @"Arthroscopic toe joint replacement",
                          @"Arthroscopic total knee replacement",
                          @"Arthroscopic wrist fusion",
                          @"Atrial septal defect closure",
                          @"Autogenic bone marrow transplant",
                          @"Back and Neck Surgery (Spinal Fusion)",
                          @"Back Surgery",
                          @"Bariatric Surgery",
                          @"Below the knee amputation",
                          @"Bilateral adrenalectomy",
                          @"Bilateral oophorectomy",
                          @"Bilateral salpingectomy",
                          @"Bilateral salpingo-oophorectomy",
                          @"Bilateral salpingostomy",
                          @"Biventricular pacemaker surgery",
                          @"Bladder augmentation",
                          @"Bone grafting",
                          @"Bone Marrow Biopsy",
                          @"Bone Marrow Transplant",
                          @"Brain Surgery (Craniotomy)",
                          @"Breast augmentation",
                          @"Breast Reconstruction",
                          @"Breast Reduction",
                          @"Bronchoscopy",
                          @"Bunion surgery",
                          @"Caldwell-Luc procedure",
                          @"Carotid artery angioplasty",
                          @"Carotid Endarterectomy",
                          @"Carpal tunnel release",
                          @"Cataract Surgery",
                          @"Cerebral aneurysm repair by clipping",
                          @"Cerebral aneurysm repair by endovascular embolization",
                          @"Cerebral aneurysm repair by occlusion and bypass",
                          @"Cerebral embolectomy",
                          @"Cervical cerclage",
                          @"Cervical discectomy",
                          @"Cervical laminectomy",
                          @"Cervical spine fusion",
                          @"Cervix conization",
                          @"Cesarean section",
                          @"Cesarean Section Delivery",
                          @"Circumferential abdominoplasty",
                          @"Cleft lip surgery",
                          @"Cleft palate surgery",
                          @"Closed reduction and external fixation of the pelvis",
                          @"Clubfoot repair",
                          @"Colectomy",
                          @"Colon Resection",
                          @"Colostomy",
                          @"Common bile duct exploration",
                          @"Cornea Transplant",
                          @"Coronary Angioplasty",
                          @"Coronary angioplasty with stent placement",
                          @"Coronary artery bypass",
                          @"Craniectomy",
                          @"Cranioplasty",
                          @"Craniotomy",
                          @"Cryosurgery for bone cancer",
                          @"Cryosurgery for liver cancer",
                          @"Cryosurgery for prostate cancer",
                          @"Cryosurgery for the cervix",
                          @"Cyst or abscess drainage",
                          @"Cystduodenostomy",
                          @"Cystectomy",
                          @"Dacryocystorhinostomy",
                          @"Debridement",
                          @"Deep brain stimulation",
                          @"Deep chemical skin peel",
                          @"Defibrillator Implant",
                          @"Dental implant surgery",
                          @"Dermabrasion",
                          @"Dilatation and Curettage",
                          @"Dilation and curettage",
                          @"Dilation and evacuation",
                          @"Dilation and extraction",
                          @"Discectomy",
                          @"Distal pancreatectomy",
                          @"Distal splenorenal shunt",
                          @"Distal subtotal gastrectomy",
                          @"Ear Tube Placement",
                          @"Electrodessication and curettage for plantar warts",
                          @"Embolization",
                          @"Empyema drainage",
                          @"End to end anastomosis for aortic coarctation",
                          @"Endonasal rhinoplasty",
                          @"Endoscopic carpal tunnel release",
                          @"Endoscopic cervical microdiscectomy",
                          @"Endoscopic craniotomy",
                          @"Endoscopic endonasal approach",
                          @"Endoscopic esophageal diverticulectomy",
                          @"Endoscopic lumbar microdiscectomy",
                          @"Endoscopic lumbar microlaminectomy",
                          @"Endovascular cardiopulmonary bypass",
                          @"Endovascular stent grafting for aortic aneurysm",
                          @"Esophageal resection",
                          @"Esophagogastrectomy",
                          @"Esophagoscopy",
                          @"Esophagostomy",
                          @"Excision tattoo removal",
                          @"External fixation of the femur",
                          @"External fixation of the fibula",
                          @"External fixation of the foot",
                          @"External fixation of the radius",
                          @"External fixation of the ulna",
                          @"External tibia fixation",
                          @"Extracranial-intracranial revascularization",
                          @"Eye globe surgery",
                          @"Eyelid reconstruction",
                          @"Eyelift",
                          @"Face lift",
                          @"Facet rhizotomy",
                          @"Facial Botox injection",
                          @"Female to male sex reassignment",
                          @"Femoral artery cannulation",
                          @"Femoral osteotomy",
                          @"Femoropopliteal bypass",
                          @"Femorotibial bypass",
                          @"Femur rodding",
                          @"Fibula rodding",
                          @"Finger fusion",
                          @"Finger joint replacement",
                          @"Fistulotomy",
                          @"Flexor or extensor tendolysis",
                          @"Flexor tendon repair",
                          @"Fontan operation",
                          @"Foot amputation",
                          @"Foot fusion",
                          @"Foot joint replacement",
                          @"Frontotemporal craniotomy",
                          @"Functional endoscopic sinus surgery",
                          @"Functional neck dissection",
                          @"Gastrectomy",
                          @"Gastric bypass surgery",
                          @"Gastroesophageal Reflux Surgery",
                          @"Glycerol injection for trigeminal neuralgia",
                          @"Heart Bypass Surgery",
                          @"Heart Transplant",
                          @"Heart Valve Repair",
                          @"Heart valve repair surgery",
                          @"Heart-lung transplant",
                          @"Heller myotomy",
                          @"Hemiarthroplasty",
                          @"Hemicolectomy",
                          @"Hemorrhoidectomy",
                          @"Hepatorrhaphy",
                          @"Hernia Repair",
                          @"Hip arthroscopy",
                          @"Hip fusion",
                          @"Hip liposuction",
                          @"Hip osteotomy",
                          @"Hip Replacement Surgery",
                          @"Hip resurfacing",
                          @"Hip surgery",
                          @"Hip synovectomy",
                          @"Humerus rodding",
                          @"Hyaluronic acid therapy",
                          @"Hysteroscopic myomectomy",
                          @"Hysteroscopy",
                          @"Ileal conduit",
                          @"Ileostomy",
                          @"Immediate limb lengthening",
                          @"Implantable cardioverter defibrillator surgery",
                          @"In Vitro Fertilization",
                          @"Indian rhinoplasty",
                          @"Infrainguinal arterial bypass",
                          @"Inguinal lymph node dissection",
                          @"Intentional replantation",
                          @"Internal colo-anal pouch",
                          @"Interstitial perineal implant treatment",
                          @"Interventional stroke treatment",
                          @"Intra-aortic balloon pump",
                          @"Intracapsular tonsillectomy",
                          @"Intracavitary brachytherapy for breast cancer",
                          @"Intradiscal electrothermal therapy",
                          @"Intramedullary fixation of the femur",
                          @"Intramedullary nailing of the tibia",
                          @"Intraosseous catheter placement",
                          @"Intraseptal alveoloplasty",
                          @"Intrathecal catheter and infusion pump placement",
                          @"Intrauterine myelomeningocele repair",
                          @"Intrauterine surgery to correct congenital cystic adenomatoid malformation",
                          @"Intrauterine surgery to remove a cervical teratoma",
                          @"Intrauterine surgery to remove a sacrococcygeal teratoma",
                          @"Intrauterine surgery to repair a congenital diaphragmatic hernia",
                          @"Intraventricular baffle to pulmonary valve",
                          @"Intraventricular tunnel repair",
                          @"Iodine 125 episcleral-plaque brachytherapy",
                          @"Italian rhinoplasty",
                          @"Jejunoileal bypass",
                          @"Kidney cyst decortication",
                          @"Kidney Transplant",
                          @"Knee arthrocentesis",
                          @"Knee arthroscopy",
                          @"Knee fusion",
                          @"Knee osteotomy",
                          @"Knee Repair Surgery (Arthroscopic ACL Meniscal Repair)",
                          @"Knee Replacement Surgery",
                          @"Knee synovectomy",
                          @"Kyphoplasty",
                          @"Laminectomy",
                          @"Laminotomy",
                          @"Laparoscopic adjustable gastric banding",
                          @"Laparoscopic adrenalectomy",
                          @"Laparoscopic appendectomy",
                          @"Laparoscopic bilateral adrenalectomy",
                          @"Laparoscopic bilateral oophorectomy",
                          @"Laparoscopic bilateral salpingectomy",
                          @"Laparoscopic bilateral salpingo-oophorectomy",
                          @"Laparoscopic bilateral salpingostomy",
                          @"Laparoscopic biliopancreatic diversion",
                          @"Laparoscopic Burch procedure for bladder neck suspension",
                          @"Laparoscopic cholecystectomy",
                          @"Laparoscopic cholecystostomy",
                          @"Laparoscopic choledochal cyst excision",
                          @"Laparoscopic choledochojejunostomy",
                          @"Laparoscopic colectomy",
                          @"Laparoscopic colostomy",
                          @"Laparoscopic common bile duct exploration",
                          @"Laparoscopic cystectomy",
                          @"Laparoscopic cystgastrostomy",
                          @"Laparoscopic cystjejunostomy",
                          @"Laparoscopic cystoprostatectomy",
                          @"Laparoscopic distal pancreatectomy",
                          @"Laparoscopic distal subtotal gastrectomy",
                          @"Laparoscopic esophageal resection",
                          @"Laparoscopic esophagogastrectomy",
                          @"Laparoscopic fundoplication",
                          @"Laparoscopic Gallbladder Removal",
                          @"Laparoscopic gastrectomy",
                          @"Laparoscopic gastric bypass surgery",
                          @"Laparoscopic gastroduodenostomy",
                          @"Laparoscopic gastrostomy",
                          @"Laparoscopic hemicolectomy",
                          @"Laparoscopic ileostomy",
                          @"Laparoscopic inguinal-femoral hernia repair",
                          @"Laparoscopic kidney cyst decortication",
                          @"Laparoscopic left lateral segmentectomy",
                          @"Laparoscopic meniscectomy",
                          @"Laparoscopic myomectomy",
                          @"Laparoscopic nephroureterectomy",
                          @"Laparoscopic oophorectomy",
                          @"Laparoscopic pancreatic pseudocyst drainage",
                          @"Laparoscopic partial colectomy",
                          @"Laparoscopic partial thyroidectomy",
                          @"Laparoscopic proctocolectomy",
                          @"Laparoscopic prophylactic oophorectomy",
                          @"Laparoscopic prostatectomy",
                          @"Laparoscopic proximal subtotal gastrectomy",
                          @"Laparoscopic pyeloplasty",
                          @"Laparoscopic pyloroplasty",
                          @"Laparoscopic radical cystoprostatectomy",
                          @"Laparoscopic radical prostatectomy",
                          @"Laparoscopic rectal prolapse surgery",
                          @"Laparoscopic retrograde cholecystectomy",
                          @"Laparoscopic salpingectomy",
                          @"Laparoscopic salpingo-oophorectomy",
                          @"Laparoscopic salpingostomy",
                          @"Laparoscopic small intestine partial resection",
                          @"Laparoscopic spigelian hernia repair",
                          @"Laparoscopic splenectomy",
                          @"Laparoscopic thyroid lobectomy",
                          @"Laparoscopic thyroidectomy",
                          @"Laparoscopic tubal ligation",
                          @"Laparoscopic umbilical hernia repair",
                          @"Laparoscopic unilateral oophorectomy",
                          @"Laparoscopic unilateral salpingectomy",
                          @"Laparoscopic unilateral salpingo-oophorectomy",
                          @"Laparoscopic unilateral salpingostomy",
                          @"Laparoscopic vagotomy",
                          @"Laparoscopic vertical banded gastroplasty",
                          @"Laparoscopic wedge resection of the liver",
                          @"Laparoscopic Whipple operation",
                          @"Laparoscopically assisted vaginal hysterectomy",
                          @"Laparotomy",
                          @"Laryngopharyngectomy",
                          @"Laryngoscopy",
                          @"Laser bronchoscopy",
                          @"Laser skin resurfacing",
                          @"LASIK",
                          @"Le Fort I osteotomy",
                          @"Le Fort II osteotomy",
                          @"Le Fort III osteotomy",
                          @"Left ventricular aneurysmectomy",
                          @"Left ventricular assist device placement",
                          @"Leg amputation",
                          @"Leg fasciotomy",
                          @"Liposuction",
                          @"Liver Biopsy",
                          @"Liver resection",
                          @"Liver transplant",
                          @"Living donor liver transplant",
                          @"Lobectomy",
                          @"Local transanal resection",
                          @"Loop electrosurgical excision procedure",
                          @"Low anterior resection",
                          @"Lumbar discectomy",
                          @"Lumbar drain placement",
                          @"Lumbar laminectomy",
                          @"Lumbar laminotomy",
                          @"Lumbar puncture",
                          @"Lumbar spine fusion",
                          @"Lumbar sympathectomy",
                          @"Lumpectomy",
                          @"Lumpectomy (Partial Mastectomy)",
                          @"Lung Biopsy",
                          @"Lung transplant",
                          @"Lung volume reduction surgery",
                          @"Magnetic resonance imaging-guided focused ultrasound surgery",
                          @"Male to female sex reassignment",
                          @"Mastectomy Total (Radical)",
                          @"Maxillary antral lavage",
                          @"Maxillary labial frenectomy",
                          @"Maxillary tori reduction",
                          @"Maxillary tuberosity reduction",
                          @"Maxillomandibular advancement",
                          @"Maze procedure",
                          @"Meniscectomy",
                          @"Microvascular decompression",
                          @"Middle fossa acoustic tumor surgery",
                          @"Mini-laparotomy tubal ligation",
                          @"Miniabdominoplasty",
                          @"Minimally invasive aortic valve repair",
                          @"Minimally invasive aortic valve replacement",
                          @"Minimally invasive bypass surgery",
                          @"Minimally invasive heart valve surgery",
                          @"Minimally invasive maze procedure",
                          @"Minimally invasive mitral valve repair",
                          @"Minimally invasive mitral valve replacement",
                          @"Minimally invasive patent foramen ovale closure",
                          @"Minimally invasive pulmonary artery valve repair",
                          @"Minimally invasive pulmonary artery valve replacement",
                          @"Minimally invasive tricuspid valve repair",
                          @"Minimally invasive tricuspid valve replacement",
                          @"Mitral valve repair surgery",
                          @"Mitral valve replacement surgery",
                          @"Modified radical mastectomy",
                          @"Modified radical mastoidectomy",
                          @"Modified radical neck dissection",
                          @"Nephrectomy",
                          @"Nephroureterectomy",
                          @"Nerve repair",
                          @"Normal Vaginal Delivery",
                          @"Ocular implant surgery",
                          @"Oculoplastic surgery",
                          @"Off-pump coronary artery bypass",
                          @"Oophorectomy",
                          @"Open bile duct surgery",
                          @"Open Bladder Surgery",
                          @"Open cholecystectomy",
                          @"Open cholecystostomy",
                          @"Open fundoplication",
                          @"Open gastrostomy",
                          @"Open inguinal-femoral hernia repair",
                          @"Open lateral release for patellar realignment",
                          @"Open maze procedure",
                          @"Open reduction and internal fixation of a foot fracture",
                          @"Open reduction and internal fixation of a tibial plateau fracture",
                          @"Open reduction and internal fixation of an ankle fracture",
                          @"Open reduction and internal fixation of distal tibia fracture",
                          @"Open reduction and internal fixation of the fibula",
                          @"Open reduction and internal fixation of the proximal humerus",
                          @"Open reduction and pinning for lateral condylar humerus fracture",
                          @"Open reduction and pinning for supracondylar humerus fracture",
                          @"Open rotator cuff repair",
                          @"Open spigelian hernia repair",
                          @"Ovary Removal Surgery (Oophorectomy)",
                          @"Pacemaker Implant",
                          @"Pacemaker surgery",
                          @"Pancreas transplant",
                          @"Pancreas-kidney transplant",
                          @"Pancreatic islet transplantation",
                          @"Panendoscopy",
                          @"Paracentesis",
                          @"Parathyroidectomy",
                          @"Partial colectomy",
                          @"Partial hip replacement",
                          @"Partial hysterectomy",
                          @"Partial knee replacement",
                          @"Partial laryngectomy",
                          @"Partial maxillectomy",
                          @"Partial nephrectomy",
                          @"Partial temporomandibular joint replacement",
                          @"Partial thyroidectomy",
                          @"Partial vulvectomy",
                          @"Patch aortoplasty for aortic coarctation",
                          @"Patent ductus arteriosus repair",
                          @"Patent ductus arteriosus repair by percutaneous coil embolization",
                          @"Patent foramen ovale closure",
                          @"Pelvic exenteration",
                          @"Penile implant",
                          @"Penile ligament release",
                          @"Pericardiectomy",
                          @"Pericardiocentesis",
                          @"Pharyngectomy",
                          @"Photodynamic laser bronchoscopy",
                          @"Photodynamic therapy for lung cancer",
                          @"Plantar fasciotomy",
                          @"Plate and screw fixation of the arm bones",
                          @"Plate and screw fixation of the femur",
                          @"Plate and screw fixation of the radius",
                          @"Plate and screw fixation of the ulna",
                          @"Pneumonectomy",
                          @"Polypectomy",
                          @"Posterior fossa decompression",
                          @"Posterior neck dissection",
                          @"Posterolateral thoracotomy",
                          @"Proctocolectomy",
                          @"Prophylactic oophorectomy",
                          @"Prostate Removal Surgery",
                          @"Prostatectomy",
                          @"Proximal row carpectomy",
                          @"Proximal subtotal gastrectomy",
                          @"Pterygium excision",
                          @"Pubic liposuction",
                          @"Pubovaginal sling surgery",
                          @"Pyloromyotomy",
                          @"Pyloroplasty",
                          @"Radial artery cannulation",
                          @"Radial keratotomy",
                          @"Radical cystoprostatectomy",
                          @"Radical hysterectomy",
                          @"Radical mastectomy",
                          @"Radical mastoidectomy",
                          @"Radical maxillectomy",
                          @"Radical neck dissection",
                          @"Radical parotidectomy",
                          @"Radical perineal prostatectomy",
                          @"Radical prostatectomy",
                          @"Radical vulvectomy",
                          @"Radiesse",
                          @"Radiofrequency ablation for bone cancer",
                          @"Radiofrequency ablation for breast cancer",
                          @"Radiofrequency ablation for esophageal dysplasia",
                          @"Radiofrequency ablation for kidney cancer",
                          @"Radiofrequency ablation for liver cancer",
                          @"Radiofrequency ablation for lung cancer",
                          @"Radiofrequency ablation for sacroiliac joint pain",
                          @"Radiofrequency occlusion",
                          @"Radiofrequency rhizotomy",
                          @"Radius rodding",
                          @"Reconstructive rhinoplasty",
                          @"Rectal prolapse surgery",
                          @"Rectal prolapse surgery by abdomen",
                          @"Repair of perforated duodenal ulcer by laparotomy",
                          @"Replantation",
                          @"Resection of hepatic duct tumor (Klatskin tumor)",
                          @"Retinal cryosurgery",
                          @"Retinal laser photocoagulation",
                          @"Revision ankle surgery",
                          @"Revision elbow surgery",
                          @"Revision hip surgery",
                          @"Revision knee surgery",
                          @"Revision shoulder surgery",
                          @"Revision wrist surgery",
                          @"Rhinoplasty",
                          @"Rhinoplasty (Nose Surgery)",
                          @"Right ventricular aneurysmectomy",
                          @"Right ventricular to pulmonary artery conduit",
                          @"Robotic cystectomy",
                          @"Robotic cystoprostatectomy",
                          @"Robotic prostatectomy",
                          @"Robotic radical cystoprostatectomy",
                          @"Robotic radical prostatectomy",
                          @"Robotic-assisted maze procedure",
                          @"Robotically-assisted atrial septal defect closure",
                          @"Robotically-assisted combined valve repair",
                          @"Robotically-assisted combined valve replacement",
                          @"Robotically-assisted coronary artery bypass",
                          @"Robotically-assisted mitral valve repair",
                          @"Robotically-assisted mitral valve replacement",
                          @"Robotically-assisted patent foramen ovale closure",
                          @"Robotically-assisted removal of cardiac tumors",
                          @"Robotically-assisted tricuspid valve repair",
                          @"Robotically-assisted tricuspid valve replacement",
                          @"Robotically-assisted ventricular septal defect closure",
                          @"Salpingectomy",
                          @"Salpingo-oophorectomy",
                          @"Salpingostomy",
                          @"Scleral buckle surgery",
                          @"Sclerotherapy",
                          @"Segmental mandibulectomy",
                          @"Septoplasty",
                          @"Septorhinoplasty",
                          @"Shoulder arthroscopy",
                          @"Shoulder replacement",
                          @"Shoulder Surgery",
                          @"Shoulder synovectomy",
                          @"Simple alveoloplasty",
                          @"Simple bilateral orchiectomy",
                          @"Simple mastectomy",
                          @"Simple unilateral orchiectomy",
                          @"Simple vulvectomy",
                          @"Sinus lift",
                          @"Sistrunk procedure",
                          @"Small intestine partial resection",
                          @"Sphincterotomy",
                          @"Spinal disc replacement surgery",
                          @"Spine fusion",
                          @"Spleen Removal Surgery (Splenectomy)",
                          @"Splenectomy",
                          @"Staging laparoscopy",
                          @"Staging laparotomy",
                          @"Stapedectomy",
                          @"Stereotactic body radiation therapy",
                          @"Stereotactic radiotherapy on the brain",
                          @"Sternotomy",
                          @"Strabismus surgery",
                          @"Subcutaneous face lift",
                          @"Submandibular gland excision",
                          @"Submucosal minimally invasive lingual excision",
                          @"Suboccipital acoustic tumor surgery",
                          @"Suboccipital craniotomy",
                          @"Subungual hematoma drainage",
                          @"Suction curettage",
                          @"Superficial chemical skin peel",
                          @"Superficial musculoaponeurotic system (SMAS) face lift",
                          @"Superficial parotidectomy",
                          @"Superior border augmentation",
                          @"Supraomohyoid neck dissection",
                          @"Surgery for abdominal aortic aneurysm",
                          @"Surgery for the removal of cardiac tumors",
                          @"Surgery to correct de Quervain's disease",
                          @"Surgical bypass",
                          @"Syme's amputation",
                          @"Tear duct probing",
                          @"Temporal craniotomy",
                          @"Temporal lobectomy",
                          @"Temporary transvenous cardiac pacing",
                          @"Temporomandibular joint arthroscopy",
                          @"Temporomandibular joint discectomy",
                          @"Tetralogy of Fallot repair",
                          @"Third molar extraction",
                          @"Thrombectomy",
                          @"Thrombolysis",
                          @"Thymectomy",
                          @"Thyroid lobectomy",
                          @"Thyroid Removal Surgery (Thyroidectomy)",
                          @"Thyroidectomy",
                          @"Tibia rodding",
                          @"Tip rhinoplasty",
                          @"Tonsils Removal Surgery (Tonsillectomy)",
                          @"Tooth extraction",
                          @"Total gastrectomy",
                          @"Total Hysterectomy",
                          @"Total knee replacement",
                          @"Total laparoscopic hysterectomy",
                          @"Total laryngectomy",
                          @"Total maxillectomy",
                          @"Total pancreatectomy",
                          @"Total parotidectomy",
                          @"Tracheal resection",
                          @"Tracheobronchial stenting",
                          @"Tracheoesophageal fistula and esophageal atresia repair",
                          @"Tracheostomy",
                          @"Tracheotomy",
                          @"Trans-urethral Bladder Surgery",
                          @"Transcatheter atrial septal defect (ASD) closure",
                          @"Transcatheter ventricular septal defect (VSD) closure",
                          @"Transmyocardial laser revascularization",
                          @"Transsphenoidal endoscopy",
                          @"Transurethral resection of the prostate",
                          @"Tricuspid valve repair surgery",
                          @"Tricuspid valve replacement surgery",
                          @"Triple bypass surgery",
                          @"Tubal Ligation",
                          @"Turbinate reduction",
                          @"Tympanomastoidectomy",
                          @"Tympanoplasty",
                          @"Unilateral oophorectomy",
                          @"Unilateral salpingectomy",
                          @"Unilateral salpingo-oophorectomy",
                          @"Unilateral salpingostomy",
                          @"Unipolar sternocleidomastoid release",
                          @"Upper extremity sympathectomy",
                          @"Urethral catheter placement",
                          @"Urinary Incontinence Repair",
                          @"Urostomy",
                          @"Uterine fibroid embolization",
                          @"Uvulopalatoplasty",
                          @"Vaginal Hysterectomy",
                          @"Vaginoplasty",
                          @"Vagus nerve stimulation",
                          @"Varicose vein surgical ligation and stripping",
                          @"Vasectomy",
                          @"Vasectomy reversal",
                          @"Vena cava filter placement",
                          @"Ventricular septal defect repair",
                          @"Ventricular shunt placement",
                          @"Vertebroplasty",
                          @"Vertical banded gastroplasty",
                          @"Vestibuloplasty",
                          @"Video-assisted lobectomy",
                          @"Vitrectomy",
                          @"Vocal cord stripping",
                          @"Vulvectomy",
                          @"Wart removal by laser therapy",
                          @"Web finger repair",
                          @"Wedge resection of the liver",
                          @"Whipple operation",
                          @"Wrist arthrocentesis",
                          @"Wrist arthroscopy",
                          @"Wrist fusion",nil];
    }
    
    return procedureArray;
}

+(NSArray*)medications
{
    if (!medicationArray) {
        medicationArray = [[NSArray alloc] initWithObjects:
                           @"Acetaminophen/Codeine",
                           @"Aciphex",
                           @"Acyclovir",
                           @"Adderall XR",
                           @"Advair Diskus",
                           @"Alendron (Fosamax)",
                           @"Allopurinol",
                           @"Alprazolam",
                           @"Amiodarone",
                           @"Amitriptyline",
                           @"Amlodipine besylate",
                           @"Amoxicillin",
                           @"Amoxicillin/Potassium Clavulanate",
                           @"Amoxil",
                           @"Amoxil (Trimox)",
                           @"Amoxil (Trimox)",
                           @"Atenolol/Chlorthalidone",
                           @"Atorvastatin Calcium (Lipitor)",
                           @"Augmentin XR",
                           @"Avalide",
                           @"Avelox",
                           @"Azithromycin (Zithromax)",
                           @"Baclofen",
                           @"Benazpril",
                           @"Benicar",
                           @"Benztropine",
                           @"Bisoprolol/HCTZ",
                           @"Budesonide Inhalation Suspension (Pulmicort Respules)",
                           @"Budesonide Nasal Spray (Rhinocort Aqua)",
                           @"Buspiron",
                           @"Captopril",
                           @"Carbamazepine",
                           @"Cefuroxime",
                           @"Cefzil",
                           @"Celecoxib Capules (Celebrex)",
                           @"Cephalexin",
                           @"Cetirizine (Zyrtec Tablets)",
                           @"Cialis",
                           @"Ciprofloxacin",
                           @"Citalopram",
                           @"Clarinex",
                           @"Clarithromycin (Biaxin XL)",
                           @"Clindamycin",
                           @"Clindamycin(Topical)",
                           @"Clonazepam",
                           @"Clonidine",
                           @"Clopidogrel Bisulfate Tablets (Plavix)",
                           @"Colchicine",
                           @"Combivent",
                           @"Coreg",
                           @"Crestor",
                           @"Cyclobenzaprine",
                           @"Cymbalta",
                           @"Digoxin",
                           @"Digoxin (Digitek)",
                           @"Diltiazem Hydrochloride (Cartia XT)",
                           @"Diovan HCT",
                           @"Diphenoxylate/Atropine",
                           @"Ditropan XL",
                           @"Divalproex Sodium (Depakote)",
                           @"Donepezil Hydrochloride  (Aricept)",
                           @"Doxepin",
                           @"Doxycycline",
                           @"Enalapril",
                           @"Esomeprazole Magnesium (Nexium)",
                           @"Estradiol",
                           @"Famotidine",
                           @"Fenofibrate (Tricor)",
                           @"Fentanyl",
                           @"Fexofenadine",
                           @"Fexofenadine (Allegra)",
                           @"Finasteride (Proscar)",
                           @"Fioricet",
                           @"Flexeril",
                           @"Flonase",
                           @"Flovent HFA",
                           @"Fluconazole",
                           @"Fluocinonide",
                           @"Fluoxetine",
                           @"Fluvastatin Sodium (Lescol XL)",
                           @"Folic Add",
                           @"Fortamet",
                           @"Fosinopril",
                           @"Furosemide",
                           @"Gabapentin",
                           @"Gemfibrozil",
                           @"Glimepiride (Amoryl)",
                           @"Glipizide",
                           @"Glyburide/Metformin",
                           @"Humulin 70/30",
                           @"Humulin N",
                           @"Hydrocodone/Acetaminophen",
                           @"Hydrocortisone",
                           @"Hydroxyzine",
                           @"Hyoscyamine",
                           @"Ibuprofen",
                           @"Inderal LA",
                           @"Indomethacin",
                           @"Insulin Lispro Injection (Humalog)",
                           @"Irbesartan (Avapro)",
                           @"Isosorbide",
                           @"Labetalol",
                           @"Lansoprazole (Prevacid)",
                           @"Lantus",
                           @"Levaquin",
                           @"Levitra",
                           @"Levonorgestrel/Ethinyl Estradiol (Aviane)",
                           @"Levothroid",
                           @"Lexapro",
                           @"Lidoderm",
                           @"Lisinopril",
                           @"Lithium Carbonate",
                           @"Lorazepam",
                           @"Lorazepam Potassium (Cozaar)",
                           @"Lorazepam Potassium-Hydrochlorothiazide (Hyzaar)",
                           @"Lotrel",
                           @"Lovastatin",
                           @"Lunesta",
                           @"Meclixine",
                           @"Metformin",
                           @"Methadose",
                           @"Methocarbamol",
                           @"Methotrexate",
                           @"Methylphenidate HCL(Concerta)",
                           @"Methylprednisolone",
                           @"Metoclopramide",
                           @"Metoprolol",
                           @"Metoprolol Succinate (Toprol-XL)",
                           @"Metronidazole Tabs",
                           @"Minocycline",
                           @"Montelukast Sodium (Singulair)",
                           @"Morphine",
                           @"Mupirocin (Bactroban)",
                           @"Naproxen",
                           @"Naproxen Sodium",
                           @"Nasonex",
                           @"Niaspan",
                           @"Nifedipine ER",
                           @"Nitroglycerin",
                           @"Nortriptyline",
                           @"Novolog",
                           @"Nystatin",
                           @"Nystatin (Topical)",
                           @"Olanzapine (Zyprexa)",
                           @"Ortho Evra",
                           @"Oseltamivir Phosphate (Tamiflu)",
                           @"Oxcarbazepine (Trileptal)",
                           @"Oxycodone",
                           @"Oxycodone w/Acetaminophen",
                           @"OxyContin",
                           @"Paroxetine",
                           @"Paxil CR",
                           @"Penicillin VK",
                           @"Phenobarbital",
                           @"Phentermine",
                           @"Phenytoin",
                           @"Phenytoin Sodium(Dilantin)",
                           @"Pioglitazone Hydrochloride (Actos)",
                           @"Pravachol",
                           @"Prednisolone",
                           @"Prednisone",
                           @"Premarin",
                           @"Prempro",
                           @"Promethazine",
                           @"Promethazine DM",
                           @"Promethazine/Codeine",
                           @"Prometrium",
                           @"Propranolol",
                           @"Protonix",
                           @"Ptopoxyphene-N/Acetaminophen",
                           @"Quinapril",
                           @"Quinine",
                           @"Ramipril (Altace)",
                           @"Ranitidine",
                           @"Risedronate Sodium (Actonel)",
                           @"Risperdal",
                           @"Rosiglitazone Maleate  (Avandia)",
                           @"Sertraline Hydrochloride (Zoloft)",
                           @"Simvastatin (Zocor)",
                           @"Sinemet",
                           @"Spiriva",
                           @"Spironolactone",
                           @"Strattera",
                           @"Sumatriptan Succinate (Imitrex)",
                           @"Tamoxifen",
                           @"Tamsulosin Hydrochloride (Flomax)",
                           @"Temazepam",
                           @"Terazosin",
                           @"Terbinafine Hydrochloride (Lamisil)",
                           @"Tetracycline",
                           @"Tolterodine Tartrate (Detrol LA)",
                           @"Topamax",
                           @"Tramadol/Acetaminophen",
                           @"Triamcinolone Acetonide (Nasacort AQ)",
                           @"Ttamadol",
                           @"Ultracet",
                           @"Valium (Diazepam)",
                           @"Valsartan (Diovan)",
                           @"Valtrex",
                           @"Venlafaxine Hydrochloride (Effexor XR)",
                           @"Ventolin Inhalation (Albuterol Aerosol)",
                           @"Ventolin Solution (Albuterol Nebulizer Sol.)",
                           @"Verapamil SR",
                           @"Viagra",
                           @"Vicoprofen",
                           @"Vytorin",
                           @"Warfarln",
                           @"Warfarln (Coumadin)",
                           @"Wellbutrin",
                           @"Yasmin",
                           @"Zestoretic",
                           @"Zolpidem Tartrate (Ambien)",
                           @"Zyrtec-D", nil];
    }
    
    return medicationArray;
}

+(NSArray*)allergies
{
    if (!allergyArray) {
        allergyArray = [[NSArray alloc] initWithObjects:
                        @"Carbamazepine",
                        @"Cephalosporins",
                        @"Codeine",
                        @"Dilantin (Phenytoin)",
                        @"I.V. contrast dye",
                        @"Latex",
                        @"Local anesthetics",
                        @"Morphine",
                        @"Non-steroidal anti-inflammatories",
                        @"Penicillin",
                        @"Sulfonamides",
                        @"Tegretol (Carbamazepine)",
                        @"Tetracycline", nil];
    }
    
    return allergyArray;
}

@end
