/*This file is generated by perlxml.pl. DO NOT MODIFY */

#import "EndocrineViewController.h"
#import "BBUtil.h"
#import "FormSection.h"
#import "FormElement.h"
#import "BBCheckBox.h"
#import "BooleanFormElement.h"
#import "StringListElement.h"
#import "TextElement.h"
#import "StringArrayTableAdapter.h"

#import "ElementListFormElement.h"

#import "FormElementTableAdapter.h"

#import "FormElementTableCellFactory.h"

#import "AntibioticFormElement.h"

#import "MedicationFormElement.h"

#import "BBData.h"

#import "BBAutoCompleteTextField.h"


@interface EndocrineViewController () <UITextFieldDelegate>
@property (weak, nonatomic) IBOutlet BBCheckBox *endocrineBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *endocrineNegativeBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *diabetesBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *diabetesTwoBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *hyperThyroidBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *hypoThyroidBBCheckBox;
@property (weak, nonatomic) IBOutlet UITextView *notesUITextView;
@end

@implementation EndocrineViewController
NSString *const ENDOCRINE_SECTION_TITLE = @"EndocrineSectionKey";
static NSString *const ENDOCRINE_KEY = @"EndocrineKey";
static NSString *const ENDOCRINE_NEGATIVE_KEY = @"EndocrineNegativeKey";
static NSString *const DIABETES_KEY = @"DiabetesKey";
static NSString *const DIABETES_TWO_KEY = @"DiabetesTwoKey";
static NSString *const HYPER_THYROID_KEY = @"HyperThyroidKey";
static NSString *const HYPO_THYROID_KEY = @"HypoThyroidKey";
static NSString *const NOTES_KEY = @"NotesKey";

- (void)viewDidLoad
{
	 [super viewDidLoad];
	 [self.endocrineBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 [self.endocrineNegativeBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 if (_section) {
		 [self validateSection:_section];
		 NSArray *elements = [_section.elements array];

		 for (FormElement *element in elements) {
			 if ([element.key isEqualToString:ENDOCRINE_KEY]){
				 [self.endocrineBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:ENDOCRINE_NEGATIVE_KEY]){
				 [self.endocrineNegativeBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:DIABETES_KEY]){
				 [self.diabetesBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:DIABETES_TWO_KEY]){
				 [self.diabetesTwoBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:HYPER_THYROID_KEY]){
				 [self.hyperThyroidBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:HYPO_THYROID_KEY]){
				 [self.hypoThyroidBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:NOTES_KEY]){
				 [self.notesUITextView setText:((TextElement*)element).value];
			 }
		 }
	 }
}


-(void)addDatePicker: (UITextField*)textField withSelector: (SEL)selector {
	 UIDatePicker *datePicker = [[UIDatePicker alloc] init];
	 datePicker.datePickerMode = UIDatePickerModeDate;
	 [textField setInputView:datePicker];
	 UIToolbar *myToolbar = [[UIToolbar alloc] initWithFrame: CGRectMake(0,0,340,44)];
	 UIBarButtonItem *doneButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:selector];
	 [myToolbar setItems:[NSArray arrayWithObject: doneButton] animated:NO];
	 textField.inputAccessoryView = myToolbar;
}

-(void)validateSection:(FormSection*)section
{
	 NSAssert([section getElementForKey:ENDOCRINE_KEY]!= nil, @"Endocrine is nil");
	 NSAssert([section getElementForKey:ENDOCRINE_NEGATIVE_KEY]!= nil, @"EndocrineNegative is nil");
	 NSAssert([section getElementForKey:DIABETES_KEY]!= nil, @"Diabetes is nil");
	 NSAssert([section getElementForKey:DIABETES_TWO_KEY]!= nil, @"DiabetesTwo is nil");
	 NSAssert([section getElementForKey:HYPER_THYROID_KEY]!= nil, @"HyperThyroid is nil");
	 NSAssert([section getElementForKey:HYPO_THYROID_KEY]!= nil, @"HypoThyroid is nil");
	 NSAssert([section getElementForKey:NOTES_KEY]!= nil, @"Notes is nil");
	 
}

-(BOOL)validateData:(NSString**)errMsg
{
	 if( self.endocrineNegativeBBCheckBox.selected ){ 
		 if( !((!self.diabetesBBCheckBox.selected) && (!self.diabetesTwoBBCheckBox.selected) && (!self.hyperThyroidBBCheckBox.selected) && (!self.hypoThyroidBBCheckBox.selected)) ){ 
			 *errMsg = @"Diabetes must be unselected and DiabetesTwo must be unselected and HyperThyroid must be unselected and HypoThyroid must be unselected when EndocrineNegative is selected"; 
			 return false; 
		 }
	 }
	 if( self.endocrineBBCheckBox.selected ){ 
		 if( !(self.diabetesBBCheckBox.selected || self.diabetesTwoBBCheckBox.selected || self.hyperThyroidBBCheckBox.selected || self.hypoThyroidBBCheckBox.selected) ){ 
			 *errMsg = @"Diabetes must be selected or DiabetesTwo must be selected or HyperThyroid must be selected or HypoThyroid must be selected when Endocrine is selected"; 
			 return false; 
		 }
	 }
	 return true; 
}

- (IBAction)accept:(id)sender {
	 NSString* errMsg;
	 if ( ! [self validateData: &errMsg] ){
		 [BBUtil showAlertWithMessage:errMsg];
		 return;
	 }
	 if ( !self.section ){
		 self.section = (FormSection*)[BBUtil newCoreDataObjectForEntityName:@"FormSection"];
		 self.section.title = ENDOCRINE_SECTION_TITLE;
	 }
	 
	 BooleanFormElement *endocrine = (BooleanFormElement*)[_section getElementForKey:ENDOCRINE_KEY];
	 if (!endocrine) {
		 endocrine = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 endocrine.key = ENDOCRINE_KEY;
		 [_section addElementsObject:endocrine];
	 }

	 endocrine.value = [NSNumber numberWithBool:self.endocrineBBCheckBox.isSelected];
	 
	 BooleanFormElement *endocrineNegative = (BooleanFormElement*)[_section getElementForKey:ENDOCRINE_NEGATIVE_KEY];
	 if (!endocrineNegative) {
		 endocrineNegative = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 endocrineNegative.key = ENDOCRINE_NEGATIVE_KEY;
		 [_section addElementsObject:endocrineNegative];
	 }

	 endocrineNegative.value = [NSNumber numberWithBool:self.endocrineNegativeBBCheckBox.isSelected];
	 
	 BooleanFormElement *diabetes = (BooleanFormElement*)[_section getElementForKey:DIABETES_KEY];
	 if (!diabetes) {
		 diabetes = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 diabetes.key = DIABETES_KEY;
		 [_section addElementsObject:diabetes];
	 }

	 diabetes.value = [NSNumber numberWithBool:self.diabetesBBCheckBox.isSelected];
	 
	 BooleanFormElement *diabetesTwo = (BooleanFormElement*)[_section getElementForKey:DIABETES_TWO_KEY];
	 if (!diabetesTwo) {
		 diabetesTwo = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 diabetesTwo.key = DIABETES_TWO_KEY;
		 [_section addElementsObject:diabetesTwo];
	 }

	 diabetesTwo.value = [NSNumber numberWithBool:self.diabetesTwoBBCheckBox.isSelected];
	 
	 BooleanFormElement *hyperThyroid = (BooleanFormElement*)[_section getElementForKey:HYPER_THYROID_KEY];
	 if (!hyperThyroid) {
		 hyperThyroid = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 hyperThyroid.key = HYPER_THYROID_KEY;
		 [_section addElementsObject:hyperThyroid];
	 }

	 hyperThyroid.value = [NSNumber numberWithBool:self.hyperThyroidBBCheckBox.isSelected];
	 
	 BooleanFormElement *hypoThyroid = (BooleanFormElement*)[_section getElementForKey:HYPO_THYROID_KEY];
	 if (!hypoThyroid) {
		 hypoThyroid = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 hypoThyroid.key = HYPO_THYROID_KEY;
		 [_section addElementsObject:hypoThyroid];
	 }

	 hypoThyroid.value = [NSNumber numberWithBool:self.hypoThyroidBBCheckBox.isSelected];
	 
	 TextElement *notes = (TextElement*)[_section getElementForKey:NOTES_KEY];
	 if (!notes) {
		 notes = (TextElement*)[BBUtil newCoreDataObjectForEntityName:@"TextElement"];
		 notes.key = NOTES_KEY;
		 [_section addElementsObject:notes];
	 }

	 notes.value = self.notesUITextView.text;
	 
	 [self.delegate sectionCreated:self.section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

- (IBAction)changeMedUnit:(UIButton*)sender {
	 if ([sender.titleLabel.text isEqualToString: @"cc"]) { 
		 [sender setTitle:@"mcg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mcg"]) {
		 [sender setTitle:@"mg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mg"]) {
		 [sender setTitle:@"G" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"G"]) {
		 [sender setTitle:@"none" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"none"]) {
		 [sender setTitle:@"cc" forState:UIControlStateNormal];
	 } 
}

- (BOOL)disablesAutomaticKeyboardDismissal {
	 return NO;
}

- (IBAction)dismiss:(id)sender {
	 [BBUtil refreshManagedObject:_section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

+(NSString*)sectionTitle
{
	 return ENDOCRINE_SECTION_TITLE;
}
-(void)radioGroup1:(BBCheckBox*)sender {
	 BOOL selected = sender.selected;
	 self.endocrineBBCheckBox.selected = NO;
	 self.endocrineNegativeBBCheckBox.selected = NO;
	 sender.selected = selected;
}
@end