/*This file is generated by perlxml.pl. DO NOT MODIFY */

#import "PastSurgicalProceduresViewController.h"
#import "BBUtil.h"
#import "FormSection.h"
#import "FormElement.h"
#import "BBCheckBox.h"
#import "BooleanFormElement.h"
#import "StringListElement.h"
#import "TextElement.h"
#import "StringArrayTableAdapter.h"

#import "ElementListFormElement.h"

#import "FormElementTableAdapter.h"

#import "FormElementTableCellFactory.h"

#import "AntibioticFormElement.h"

#import "MedicationFormElement.h"

#import "BBData.h"

#import "BBAutoCompleteTextField.h"


@interface PastSurgicalProceduresViewController () <UITextFieldDelegate>
@property (weak, nonatomic) IBOutlet BBAutoCompleteTextField *pastSurgicalProceduresTextField;
@property (weak, nonatomic) IBOutlet UITableView *pastSurgicalProceduresTable;
@property (strong, nonatomic) StringArrayTableAdapter *pastSurgicalProceduresTableAdapter;
@property (weak, nonatomic) IBOutlet BBCheckBox *hxAnesthesiaProblemsYesPatientBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *hxAnesthesiaProblemsYesFamilyBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *hxAnesthesiaProblemsNoBBCheckBox;
@property (weak, nonatomic) IBOutlet UITextView *notesUITextView;
@end

@implementation PastSurgicalProceduresViewController
NSString *const PAST_SURGICAL_PROCEDURES_SECTION_TITLE = @"PastSurgicalProceduresSectionKey";
static NSString *const PAST_SURGICAL_PROCEDURES_KEY = @"PastSurgicalProceduresKey";
static NSString *const HX_ANESTHESIA_PROBLEMS_YES_PATIENT_KEY = @"HxAnesthesiaProblemsYesPatientKey";
static NSString *const HX_ANESTHESIA_PROBLEMS_YES_FAMILY_KEY = @"HxAnesthesiaProblemsYesFamilyKey";
static NSString *const HX_ANESTHESIA_PROBLEMS_NO_KEY = @"HxAnesthesiaProblemsNoKey";
static NSString *const NOTES_KEY = @"NotesKey";

- (void)viewDidLoad
{
	 [super viewDidLoad];
	 [_pastSurgicalProceduresTextField setAutoCompleteData:[BBData procedures]];
	 [self.hxAnesthesiaProblemsYesPatientBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 [self.hxAnesthesiaProblemsYesFamilyBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 [self.hxAnesthesiaProblemsNoBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 self.pastSurgicalProceduresTableAdapter = [[StringArrayTableAdapter alloc] init];
	 self.pastSurgicalProceduresTable.dataSource = self.pastSurgicalProceduresTableAdapter;
	 self.pastSurgicalProceduresTable.delegate = self.pastSurgicalProceduresTableAdapter;

	 if (_section) {
		 [self validateSection:_section];
		 NSArray *elements = [_section.elements array];

		 for (FormElement *element in elements) {
			 if ([element.key isEqualToString:PAST_SURGICAL_PROCEDURES_KEY]){
				 self.pastSurgicalProceduresTableAdapter.items = [[NSMutableArray alloc] initWithArray:((StringListElement*)element).value];
				 [self.pastSurgicalProceduresTable reloadData];
			 }
			 if ([element.key isEqualToString:HX_ANESTHESIA_PROBLEMS_YES_PATIENT_KEY]){
				 [self.hxAnesthesiaProblemsYesPatientBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:HX_ANESTHESIA_PROBLEMS_YES_FAMILY_KEY]){
				 [self.hxAnesthesiaProblemsYesFamilyBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:HX_ANESTHESIA_PROBLEMS_NO_KEY]){
				 [self.hxAnesthesiaProblemsNoBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:NOTES_KEY]){
				 [self.notesUITextView setText:((TextElement*)element).value];
			 }
		 }
	 }
}


-(void)addDatePicker: (UITextField*)textField withSelector: (SEL)selector {
	 UIDatePicker *datePicker = [[UIDatePicker alloc] init];
	 datePicker.datePickerMode = UIDatePickerModeDate;
	 [textField setInputView:datePicker];
	 UIToolbar *myToolbar = [[UIToolbar alloc] initWithFrame: CGRectMake(0,0,340,44)];
	 UIBarButtonItem *doneButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:selector];
	 [myToolbar setItems:[NSArray arrayWithObject: doneButton] animated:NO];
	 textField.inputAccessoryView = myToolbar;
}

-(void)validateSection:(FormSection*)section
{
	 NSAssert([section getElementForKey:PAST_SURGICAL_PROCEDURES_KEY]!= nil, @"PastSurgicalProcedures is nil");
	 NSAssert([section getElementForKey:HX_ANESTHESIA_PROBLEMS_YES_PATIENT_KEY]!= nil, @"HxAnesthesiaProblemsYesPatient is nil");
	 NSAssert([section getElementForKey:HX_ANESTHESIA_PROBLEMS_YES_FAMILY_KEY]!= nil, @"HxAnesthesiaProblemsYesFamily is nil");
	 NSAssert([section getElementForKey:HX_ANESTHESIA_PROBLEMS_NO_KEY]!= nil, @"HxAnesthesiaProblemsNo is nil");
	 NSAssert([section getElementForKey:NOTES_KEY]!= nil, @"Notes is nil");
	 
}

-(BOOL)validateData:(NSString**)errMsg
{
	 return true; 
}

- (IBAction)accept:(id)sender {
	 NSString* errMsg;
	 if ( ! [self validateData: &errMsg] ){
		 [BBUtil showAlertWithMessage:errMsg];
		 return;
	 }
	 if ( !self.section ){
		 self.section = (FormSection*)[BBUtil newCoreDataObjectForEntityName:@"FormSection"];
		 self.section.title = PAST_SURGICAL_PROCEDURES_SECTION_TITLE;
	 }
	 
	 StringListElement *pastSurgicalProcedures = (StringListElement*)[_section getElementForKey:PAST_SURGICAL_PROCEDURES_KEY];
	 if (!pastSurgicalProcedures) {
		 pastSurgicalProcedures = (StringListElement*)[BBUtil newCoreDataObjectForEntityName:@"StringListElement"];
		 pastSurgicalProcedures.key = PAST_SURGICAL_PROCEDURES_KEY;
		 [_section addElementsObject:pastSurgicalProcedures];
	 }

	 NSMutableArray *pastSurgicalProceduresStringArray = [[NSMutableArray alloc] init];
	 for (int i = 0; i < [self.pastSurgicalProceduresTable numberOfRowsInSection:0]; i++){
		 UITableViewCell *cell = [self.pastSurgicalProceduresTable cellForRowAtIndexPath:[NSIndexPath indexPathForRow:i inSection:0]];
		 [pastSurgicalProceduresStringArray addObject:cell.textLabel.text];
	 }
	 pastSurgicalProcedures.value = pastSurgicalProceduresStringArray;
	 
	 BooleanFormElement *hxAnesthesiaProblemsYesPatient = (BooleanFormElement*)[_section getElementForKey:HX_ANESTHESIA_PROBLEMS_YES_PATIENT_KEY];
	 if (!hxAnesthesiaProblemsYesPatient) {
		 hxAnesthesiaProblemsYesPatient = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 hxAnesthesiaProblemsYesPatient.key = HX_ANESTHESIA_PROBLEMS_YES_PATIENT_KEY;
		 [_section addElementsObject:hxAnesthesiaProblemsYesPatient];
	 }

	 hxAnesthesiaProblemsYesPatient.value = [NSNumber numberWithBool:self.hxAnesthesiaProblemsYesPatientBBCheckBox.isSelected];
	 
	 BooleanFormElement *hxAnesthesiaProblemsYesFamily = (BooleanFormElement*)[_section getElementForKey:HX_ANESTHESIA_PROBLEMS_YES_FAMILY_KEY];
	 if (!hxAnesthesiaProblemsYesFamily) {
		 hxAnesthesiaProblemsYesFamily = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 hxAnesthesiaProblemsYesFamily.key = HX_ANESTHESIA_PROBLEMS_YES_FAMILY_KEY;
		 [_section addElementsObject:hxAnesthesiaProblemsYesFamily];
	 }

	 hxAnesthesiaProblemsYesFamily.value = [NSNumber numberWithBool:self.hxAnesthesiaProblemsYesFamilyBBCheckBox.isSelected];
	 
	 BooleanFormElement *hxAnesthesiaProblemsNo = (BooleanFormElement*)[_section getElementForKey:HX_ANESTHESIA_PROBLEMS_NO_KEY];
	 if (!hxAnesthesiaProblemsNo) {
		 hxAnesthesiaProblemsNo = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 hxAnesthesiaProblemsNo.key = HX_ANESTHESIA_PROBLEMS_NO_KEY;
		 [_section addElementsObject:hxAnesthesiaProblemsNo];
	 }

	 hxAnesthesiaProblemsNo.value = [NSNumber numberWithBool:self.hxAnesthesiaProblemsNoBBCheckBox.isSelected];
	 
	 TextElement *notes = (TextElement*)[_section getElementForKey:NOTES_KEY];
	 if (!notes) {
		 notes = (TextElement*)[BBUtil newCoreDataObjectForEntityName:@"TextElement"];
		 notes.key = NOTES_KEY;
		 [_section addElementsObject:notes];
	 }

	 notes.value = self.notesUITextView.text;
	 
	 [self.delegate sectionCreated:self.section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

- (IBAction)changeMedUnit:(UIButton*)sender {
	 if ([sender.titleLabel.text isEqualToString: @"cc"]) { 
		 [sender setTitle:@"mcg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mcg"]) {
		 [sender setTitle:@"mg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mg"]) {
		 [sender setTitle:@"G" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"G"]) {
		 [sender setTitle:@"none" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"none"]) {
		 [sender setTitle:@"cc" forState:UIControlStateNormal];
	 } 
}

- (IBAction)addPastSurgicalProcedures:(id)sender {
	 [self.pastSurgicalProceduresTableAdapter.items addObject:self.pastSurgicalProceduresTextField.text];
	 [self.pastSurgicalProceduresTable reloadData];
	 self.pastSurgicalProceduresTextField.text = @"";
	 [self.pastSurgicalProceduresTextField resignFirstResponder];
}

- (BOOL)disablesAutomaticKeyboardDismissal {
	 return NO;
}

- (IBAction)dismiss:(id)sender {
	 [BBUtil refreshManagedObject:_section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

+(NSString*)sectionTitle
{
	 return PAST_SURGICAL_PROCEDURES_SECTION_TITLE;
}
-(void)radioGroup1:(BBCheckBox*)sender {
	 BOOL selected = sender.selected;
	 self.hxAnesthesiaProblemsYesPatientBBCheckBox.selected = NO;
	 self.hxAnesthesiaProblemsYesFamilyBBCheckBox.selected = NO;
	 self.hxAnesthesiaProblemsNoBBCheckBox.selected = NO;
	 sender.selected = selected;
}
@end