/*This file is generated by perlxml.pl. DO NOT MODIFY */

#import "RenalViewController.h"
#import "BBUtil.h"
#import "FormSection.h"
#import "FormElement.h"
#import "BBCheckBox.h"
#import "BooleanFormElement.h"
#import "StringListElement.h"
#import "TextElement.h"
#import "StringArrayTableAdapter.h"

#import "ElementListFormElement.h"

#import "FormElementTableAdapter.h"

#import "FormElementTableCellFactory.h"

#import "AntibioticFormElement.h"

#import "MedicationFormElement.h"

#import "BBData.h"

#import "BBAutoCompleteTextField.h"


@interface RenalViewController () <UITextFieldDelegate>
@property (weak, nonatomic) IBOutlet BBCheckBox *renalBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *renalNegativeBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *cRIBBCheckBox;
@property (weak, nonatomic) IBOutlet BBCheckBox *renalFailureBBCheckBox;
@property (weak, nonatomic) IBOutlet UITextField *lastDialysisUITextField;
@property (weak, nonatomic) IBOutlet UITextView *notesUITextView;
@end

@implementation RenalViewController
NSString *const RENAL_SECTION_TITLE = @"RenalSectionKey";
static NSString *const RENAL_KEY = @"RenalKey";
static NSString *const RENAL_NEGATIVE_KEY = @"RenalNegativeKey";
static NSString *const CRI_KEY = @"CRIKey";
static NSString *const RENAL_FAILURE_KEY = @"RenalFailureKey";
static NSString *const LAST_DIALYSIS_KEY = @"LastDialysisKey";
static NSString *const NOTES_KEY = @"NotesKey";

- (void)viewDidLoad
{
	 [super viewDidLoad];

	 [self addDatePicker: self.lastDialysisUITextField withSelector: @selector(updatelastDialysisUITextField)];
	 [self.renalBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 [self.renalNegativeBBCheckBox addTarget:self action:@selector(radioGroup1:) forControlEvents:UIControlEventTouchUpInside];
	 if (_section) {
		 [self validateSection:_section];
		 NSArray *elements = [_section.elements array];

		 for (FormElement *element in elements) {
			 if ([element.key isEqualToString:RENAL_KEY]){
				 [self.renalBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:RENAL_NEGATIVE_KEY]){
				 [self.renalNegativeBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:CRI_KEY]){
				 [self.cRIBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:RENAL_FAILURE_KEY]){
				 [self.renalFailureBBCheckBox setSelected:[((BooleanFormElement*)element).value boolValue]];
			 }
			 if ([element.key isEqualToString:LAST_DIALYSIS_KEY]){
				 [self.lastDialysisUITextField setText:((TextElement*)element).value];
			 }
			 if ([element.key isEqualToString:NOTES_KEY]){
				 [self.notesUITextView setText:((TextElement*)element).value];
			 }
		 }
	 }
}


-(void)addDatePicker: (UITextField*)textField withSelector: (SEL)selector {
	 UIDatePicker *datePicker = [[UIDatePicker alloc] init];
	 datePicker.datePickerMode = UIDatePickerModeDate;
	 [textField setInputView:datePicker];
	 UIToolbar *myToolbar = [[UIToolbar alloc] initWithFrame: CGRectMake(0,0,340,44)];
	 UIBarButtonItem *doneButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:selector];
	 [myToolbar setItems:[NSArray arrayWithObject: doneButton] animated:NO];
	 textField.inputAccessoryView = myToolbar;
}

-(void)updatelastDialysisUITextField{
	 UIDatePicker *picker = (UIDatePicker*)self.lastDialysisUITextField.inputView;
	 NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
	 [dateFormatter setDateFormat:@"MM/dd/yyyy"];
	 self.lastDialysisUITextField.text = [NSString stringWithFormat:@"%@",[dateFormatter stringFromDate:picker.date]];
	 [self.lastDialysisUITextField resignFirstResponder];
}

-(void)validateSection:(FormSection*)section
{
	 NSAssert([section getElementForKey:RENAL_KEY]!= nil, @"Renal is nil");
	 NSAssert([section getElementForKey:RENAL_NEGATIVE_KEY]!= nil, @"RenalNegative is nil");
	 NSAssert([section getElementForKey:CRI_KEY]!= nil, @"CRI is nil");
	 NSAssert([section getElementForKey:RENAL_FAILURE_KEY]!= nil, @"RenalFailure is nil");
	 NSAssert([section getElementForKey:LAST_DIALYSIS_KEY]!= nil, @"LastDialysis is nil");
	 NSAssert([section getElementForKey:NOTES_KEY]!= nil, @"Notes is nil");
	 
}

-(BOOL)validateData:(NSString**)errMsg
{
	 if( self.renalNegativeBBCheckBox.selected ){ 
		 if( !((!self.cRIBBCheckBox.selected) && (!self.renalFailureBBCheckBox.selected)) ){ 
			 *errMsg = @"CRI must be unselected and RenalFailure must be unselected when RenalNegative is selected"; 
			 return false; 
		 }
	 }
	 if( self.renalBBCheckBox.selected ){ 
		 if( !(self.cRIBBCheckBox.selected || self.renalFailureBBCheckBox.selected) ){ 
			 *errMsg = @"CRI must be selected or RenalFailure must be selected when Renal is selected"; 
			 return false; 
		 }
	 }
	 if( self.renalFailureBBCheckBox.selected ){ 
		 if( !(![self.lastDialysisUITextField.text isEqualToString:@""]) ){ 
			 *errMsg = @"LastDialysis must be not empty when RenalFailure is selected"; 
			 return false; 
		 }
	 }
	 return true; 
}

- (IBAction)accept:(id)sender {
	 NSString* errMsg;
	 if ( ! [self validateData: &errMsg] ){
		 [BBUtil showAlertWithMessage:errMsg];
		 return;
	 }
	 if ( !self.section ){
		 self.section = (FormSection*)[BBUtil newCoreDataObjectForEntityName:@"FormSection"];
		 self.section.title = RENAL_SECTION_TITLE;
	 }
	 
	 BooleanFormElement *renal = (BooleanFormElement*)[_section getElementForKey:RENAL_KEY];
	 if (!renal) {
		 renal = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 renal.key = RENAL_KEY;
		 [_section addElementsObject:renal];
	 }

	 renal.value = [NSNumber numberWithBool:self.renalBBCheckBox.isSelected];
	 
	 BooleanFormElement *renalNegative = (BooleanFormElement*)[_section getElementForKey:RENAL_NEGATIVE_KEY];
	 if (!renalNegative) {
		 renalNegative = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 renalNegative.key = RENAL_NEGATIVE_KEY;
		 [_section addElementsObject:renalNegative];
	 }

	 renalNegative.value = [NSNumber numberWithBool:self.renalNegativeBBCheckBox.isSelected];
	 
	 BooleanFormElement *cRI = (BooleanFormElement*)[_section getElementForKey:CRI_KEY];
	 if (!cRI) {
		 cRI = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 cRI.key = CRI_KEY;
		 [_section addElementsObject:cRI];
	 }

	 cRI.value = [NSNumber numberWithBool:self.cRIBBCheckBox.isSelected];
	 
	 BooleanFormElement *renalFailure = (BooleanFormElement*)[_section getElementForKey:RENAL_FAILURE_KEY];
	 if (!renalFailure) {
		 renalFailure = (BooleanFormElement*)[BBUtil newCoreDataObjectForEntityName:@"BooleanFormElement"];
		 renalFailure.key = RENAL_FAILURE_KEY;
		 [_section addElementsObject:renalFailure];
	 }

	 renalFailure.value = [NSNumber numberWithBool:self.renalFailureBBCheckBox.isSelected];
	 
	 TextElement *lastDialysis = (TextElement*)[_section getElementForKey:LAST_DIALYSIS_KEY];
	 if (!lastDialysis) {
		 lastDialysis = (TextElement*)[BBUtil newCoreDataObjectForEntityName:@"TextElement"];
		 lastDialysis.key = LAST_DIALYSIS_KEY;
		 [_section addElementsObject:lastDialysis];
	 }

	 lastDialysis.value = self.lastDialysisUITextField.text;
	 
	 TextElement *notes = (TextElement*)[_section getElementForKey:NOTES_KEY];
	 if (!notes) {
		 notes = (TextElement*)[BBUtil newCoreDataObjectForEntityName:@"TextElement"];
		 notes.key = NOTES_KEY;
		 [_section addElementsObject:notes];
	 }

	 notes.value = self.notesUITextView.text;
	 
	 [self.delegate sectionCreated:self.section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

- (IBAction)changeMedUnit:(UIButton*)sender {
	 if ([sender.titleLabel.text isEqualToString: @"cc"]) { 
		 [sender setTitle:@"mcg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mcg"]) {
		 [sender setTitle:@"mg" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"mg"]) {
		 [sender setTitle:@"G" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"G"]) {
		 [sender setTitle:@"none" forState:UIControlStateNormal];
	 } else if ([sender.titleLabel.text isEqualToString: @"none"]) {
		 [sender setTitle:@"cc" forState:UIControlStateNormal];
	 } 
}

- (BOOL)disablesAutomaticKeyboardDismissal {
	 return NO;
}

- (IBAction)dismiss:(id)sender {
	 [BBUtil refreshManagedObject:_section];
	 [self dismissViewControllerAnimated:YES completion:nil];
}

+(NSString*)sectionTitle
{
	 return RENAL_SECTION_TITLE;
}
-(void)radioGroup1:(BBCheckBox*)sender {
	 BOOL selected = sender.selected;
	 self.renalBBCheckBox.selected = NO;
	 self.renalNegativeBBCheckBox.selected = NO;
	 sender.selected = selected;
}
@end